name: Build and Deploy Docker Image for VisionService

on:
  push:
    branches: [ "main" ]
    paths:
      - "VisionService/**"
      - ".github/workflows/docker-deploy.yml"

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint (flake8) for VisionService
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install flake8
          flake8 VisionService

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ecolensacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        working-directory: VisionService
        run: |
          IMAGE_NAME=ecolensacr.azurecr.io/vision-service
          IMAGE_TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'ecolensacr.azurecr.io/vision-service:${{ github.sha }}'
          format: 'table'
          vuln-type: 'os,library'
          severity: 'CRITICAL'
          ignore-unfixed: true
          exit-code: '1'

      - name: Push Docker image
        run: |
          IMAGE_NAME=ecolensacr.azurecr.io/vision-service
          IMAGE_TAG=${{ github.sha }}
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "ecolens-vision-team06"
          publish-profile: ${{ secrets.AZURE_PYTHON_PUBLISH_PROFILE }}
          images: 'ecolensacr.azurecr.io/vision-service:${{ github.sha }}'
