name: Build and Deploy Docker Image for VisionService

on:
  push:
    branches: [ "main" ]
    paths:
      - "VisionService/**"
      - ".github/workflows/docker-deploy.yml"

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ecolensacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker image
        working-directory: VisionService
        run: |
          IMAGE_NAME=ecolensacr.azurecr.io/vision-service
          IMAGE_TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "ecolens-vision-team06"
          publish-profile: ${{ secrets.AZURE_PYTHON_PUBLISH_PROFILE }}
          images: 'ecolensacr.azurecr.io/vision-service:${{ github.sha }}'
